### ISSUE TITLE
Support exports to PowerPoint (Experimental)

### ISSUE THREAD

**Issue by codecounselor** [fraserxu/electron-pdf#111]
#### When the output file has a `.ppt` or `.pptx` extension
  - First render the url as a pdf and capture an image of each page.
    - Sending to PDF honors CSS page breaks, and automatically breaks tables and includes the table headers on each subsequent page.  This is more straight forward than trying to manipulate the view and capture images.
  - Scale the image to fit on the slide, maintain the aspect ratio
  - If multiple input URLs are passed, append them to the presentation in the order they were passed
  - If a URL results in multiple pages in the PDF document, insert one page per slide.
  - Return the powerpoint document location or buffer, then delete all intermediate (pdf,png) files

## Risks

- https://github.com/Ziv-Barber/officegen appears to be the best JS library for generating pptx, but it does not (yet) support setting the slide dimensions (for higher resolution output)
  - https://github.com/Ziv-Barber/officegen/issues/112 details this

## Options for PDF to PNG conversion

1. Load PDF inside of Electron browser window and capture images
  - Mozilla's pdf.js - https://www.npmjs.com/package/pdfjs-dist - targeted at rendering PDF on a Canvas
  - https://www.npmjs.com/package/pdf-to-png (Uses Electron)
2. Do it with node libraries that rely on *nix packages
  - Portability when not using containers should be considered. `apt-get install -y imagemagick ghostscript poppler-utils GraphicsMagick`
  - Some Options:
    - pdf-image: [npm](https://www.npmjs.com/package/pdf-image) | [github](https://github.com/mooz/node-pdf-image)
      - https://www.npmjs.com/package/pdf2images-multiple (dependent)
    - https://www.npmjs.com/package/pdf2img

**Comment by fraserxu** [comment]
This sound exciting! Thanks for the great work @codecounselor .

As for exporting `.ppt` and `.pptx`, this sounds a very special use case for me. 

Do you think we can make this functionality a separate module, that works similar to what electron-pdf, that only does pdf2ppt or pdf2pptx. 

And say if a user ever want to convert a markdown file to ppt, we use `electron-pdf` to convert it to a `pdf` first, and then user the `pdf2ppt` module to take over the work. This could be done either:

1. call `pdf2ppt` inside `electron-pdf`, and we use it by make it a dependency of `electron-pdf`
2. we separate this into 2 steps, and pass the result to `pdf2ppt` module. 

We can discuss what tool we use for `pdf2ppt` later but I'd like to address how we approach to this problem first, what do you think?

**Comment by codecounselor** [comment]
I got this working today, I will probably push that later tonight.  Separating it sounds good on paper for sure.  But my use case is such that I may have a lot (> 100) of multi-page PDFs to turn into images and stick in a powerpoint.  Being able to multi-thread that in a single process is why I'd like to leave it here for now.  I'll follow up with more details in a later post, but maybe we could have some ENV settings to disable certain features if people don't want them.

As for the tools, I'm using `pdf2images-multiple` to split the PDF into images.  Turns out pdf.js isn't really meant for that purpose.

**Comment by codecounselor** [comment]
Come to think of it, maybe if we just emit events when files are ready the powerpoint and pdf splitting could be somewhere else.  I will try that

**Comment by codecounselor** [comment]
`runExport` now fires `pdf-complete` after each PDF is available on the filesystem with an object containing the property `file` pointing to the PDF on the local filesystem

**Comment by codecounselor** [comment]
I have created https://github.com/SpiderStrategies/pdf-powerpoint in order to perform the PDF->PPTX conversion
