### ISSUE TITLE
Print css is not working

### ISSUE THREAD

**Issue by jaydave** [fraserxu/electron-pdf#124]
adding css in html 
`<link rel="stylesheet" type="text/css" href="test.css" media="print">`

Here is css file content

```
@page {
   size: 8.5in 11in;    
   margin: 70pt 60pt 70pt;
}
```

When run `electron-pdf http://localhost/test.html  test.pdf`, print css is not getting applied

**Comment by codecounselor** [comment]
This sounds like an issue or limitation with Electron/Chromium.  I'm not sure electron-pdf can change this behavior.

I'm also not a CSS expert, is this to size the page when you print? Why not just use the printToPDF options to specify the PDF size of Letter? Did you try the different margin options?

```
    -p | --pageSize            String - Can be A3, A4, A5, Legal, Letter, Tabloid or an Object containing height and width in microns
                                "A4" - default
    -l | --landscape           Boolean - true for landscape, false for portrait.
                                 false - default
    -m | --marginsType          Integer - Specify the type of margins to use
                                 0 - default
                                 1 - none
                                 2 - minimum
```
