### ISSUE TITLE
`.1` is always appended in the output path

### ISSUE THREAD

**Issue by IonicaBizau** [fraserxu/electron-pdf#129]
Thanks for the great app! :sparkles: 

I have a problem: the output path becomes `<specified-path>.1`. For instance:

```sh
electron-pdf path/to/RESULTS.md pdfs/results.pdf -c pdfs/assets/gh-markdown.css
```

Generates `pdfs/results.pdf.1`, but it actually contains the Markdown code, not the interpreted MD code.

Any ideas? Looks like a bug.

**Comment by codecounselor** [comment]
You're right, I will change this if there is only a single PDF.  The API supports multiple URLs but there is no need to add a suffix for a single file.

**Comment by IonicaBizau** [comment]
And probably it would be better to add the `1` *before* the `.pdf` extension: `pdfs/results.1.pdf`.

**Comment by codecounselor** [comment]
@IonicaBizau 1.0.0 is in npm now, see if this solves your issues.

**Comment by IonicaBizau** [comment]
Thanks! Looking at the diff, that should be fixed. I cannot test it right now.
