### ISSUE TITLE
Incrorrectly draw multipage tables

### ISSUE THREAD

**Issue by johndoejdg** [fraserxu/electron-pdf#148]
Electron-pdf
![image](https://cloud.githubusercontent.com/assets/2064465/21455851/b0b89e30-c934-11e6-9457-fad9229f7f3a.png)

Chrome 55 (print mode)
![image](https://cloud.githubusercontent.com/assets/2064465/21455861/bfc68234-c934-11e6-97bd-90b7538f05b6.png)

**Comment by johndoejdg** [comment]
Fixed by adding: -p "A4" -m 0

**Comment by codecounselor** [comment]
To my knowledge this is a (re-occuring/regression) bug in Chromium.
https://bugs.chromium.org/p/chromium/issues/detail?id=669690 

Looks like you found a workaround, but I'm hoping the bug is resolved soon in Electron.
