### ISSUE TITLE
Produces a blank PDF file via CLI

### ISSUE THREAD

**Issue by lauri-elevant** [fraserxu/electron-pdf#173]
Steps to reproduce:

1. Build the 'reference' docker machine: https://github.com/fraserxu/docker-tape-run
2. Run the built image, `exec -it` into the machine with `sh`
3. `npm install --unsafe-perm electron-pdf -g`
4. `Xvfb -ac -screen scrn 1280x2000x24 :9.0 & export DISPLAY=:9.0`
5. `electron-pdf http://neti.ee test.pdf`

Produces an empty PDF file of 661 bytes in length.

Electron PDF version v1.1.9
Electron 1.4.15

**Comment by lauri-elevant** [comment]
The file produced:
[\.pdf](https://github.com/fraserxu/electron-pdf/files/780012/default.pdf)

As an additional note, an image built around a month ago is working fine (v1.1.1). 

So I went and moved my way up from there and verified that:
 - v1.1.1 works
 - v1.1.2 works
 - v1.1.5 works
 - v1.1.6 works
 - v1.1.7 works
 - v1.1.8 **breaks**

**Comment by codecounselor** [comment]
I will try to look into this soon, but I suspect it must be related to this change
https://github.com/fraserxu/electron-pdf/commit/70cac7d85bb69e6680a4e03fe7bd3c1296a5aa73#diff-ca0cd9cd02aa5e7bff8d7b5f8883f2c3L122

I haven't seen any problem though, is it only empty when you are running it in a docker container?

**Comment by lauri-elevant** [comment]
Thanks for a quick reply. Holding on to the last good version is fine for us for the time being.

I have not tried to run in on the host machine. Given a somewhat special setup with the window managers, I doubt the results will be representative :) The `fraserxu/docker-tape-run` exhibits this issue reliably, though..

**Comment by lauri-elevant** [comment]
And it seems to have this issue on any URL I tried, google.com etc.

**Comment by codecounselor** [comment]
ok, good to know.  I have no idea how folks are using this library, but I will now also try to add an automated test that runs using `docker-tape-run` so Travis can at least be on the lookout for us.
Also would happily accept PRs for any tests folks want to contribute based on their usage

**Comment by codecounselor** [comment]
Fixed in 1.2.0

**Comment by cr05s19xx** [comment]
I still think this issue has not been resolved

**Comment by marcosbaroni** [comment]
I am having this same issue (v 1.2.5).
It works when I call it using the absolute path for file.
