### ISSUE TITLE
printBackground option is currently defaulting to true

### ISSUE THREAD

**Issue by LeoHexspoor** [fraserxu/electron-pdf#180]
The  -b | --printBackground option is documented to be default set to false, but it's actually set to true. (see options file). I've not found a way to set it to false via the command line.

Is this on purpose and is the documentation wrong or is this a bug in the defaults?
If it is on purpose how do you disable printing background via the command line arguments?

**Comment by codecounselor** [comment]
well I wrote out a whole response to this but now its not here.  In short..

It has always been this way.  I will work on a fix when I get a moment.
But have you tried setting `--printBackground=true`? looking at the code and the minimist examples I think that should work.

**Comment by LeoHexspoor** [comment]
The issue is not setting it to true because it is always true. I can't find a way to set it to false. The default in the options file is set to true.

So the documentation of the project says the default is false. But the code says the default is true.

Using minimist supplying --printBackground would also sets the option to true. I have not found a way to set a boolean to false using the minimalist library. For example supplying --printBackground=false ends up passing in the string 'false' instead of a boolean and it failed to print a pdf entirely.

**Comment by codecounselor** [comment]
ok, thats a bug that is easy to fix.  instead of `booleans` in `options.js` it should just be `boolean` - I noticed that this morning looking at the minimist docs;  I obviously made a mistake implementing that. 

I can't get to it right now, but if you want to test that locally and submit a PR I will merge it in
