### ISSUE TITLE
electron-pdf returns successfully, but file isn't created

### ISSUE THREAD

**Issue by fabdrol** [fraserxu/electron-pdf#181]
I'm using `electron-pdf` on CLI on ubuntu 14.04. The process runs, returns successfully (exit code = 0), but the PDF file is not created. 

The command I run: `/path/to/electron-pdf "http://localhost:1470/api/v1/debt/58cc28ff1053451d05afa5fc,58cc28ff1053451d05afa5f9/letters" "/home/decipher/apps/debdeck-app/pdf/a02c088d63bac6e44f4743e52a0a4d135244f843.pdf"`

The result: `File "/home/decipher/apps/debdeck-app/pdf/a02c088d63bac6e44f4743e52a0a4d135244f843.pdf" doesn't exist`

Any ideas?

**Comment by codecounselor** [comment]
Nothing off the top of my head, but if you want to see more log output here is some help on how to do that:
(I am going to add a ticket to improve the logging for people using the CLI because it just occurred to me there isn't a simple way to see them.)
https://github.com/fraserxu/electron-pdf/issues/176#issuecomment-280690252
Since you're using the CLI you'll have to modify `lib/charge.js`.  

I don't think there is anything special in the code regarding commas, but have you tried a URL without a comma in it?

**Comment by fabdrol** [comment]
@codecounselor yeah, doesn't do anything either. I just re-read the README, and I think it might be the graphical environment thing. I'm spawning `electron-pdf` in a node.js service, do I need to spawn the xserver there as well?

**Comment by codecounselor** [comment]
have you seen https://github.com/fraserxu/electron-pdf/issues/36?

**Comment by fabdrol** [comment]
I just figured it out.. I needed to install a bunch of dependencies for V8 (libgtk, libssn, libasound2, etc)

**Comment by codecounselor** [comment]
Good call, this is well documented other places.  For future reference of anyone who finds this issue, this is what I had configured in a `Dockerfile` a little while back when I was starting to test electron-pdf across a variety of platforms.

```
RUN apt-get update && \
  apt-get install -y \
# Required for Headless Electron/Chromium Rendering
  libgconf2-4 libxss1 libxtst6 libnss3 libasound2 xvfb dbus-x11 libgtk2.0-common \
# Used for PDF->PNG splitting by pdf2images-multiple
  imagemagick ghostscript poppler-utils && \
# Get rid of files we don't need
  rm -rf /var/lib/apt/lists/*
```

I had commented this out, but some may need them:
```
# libnotify4 xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic fonts-font-awesome fonts-takao-mincho
```

**Comment by lucioaguiar** [comment]
I'm having a similar problem, I'm using electron-pdf version 10.0.2 on Debian 10, but when I try to use the command it doesn't do anything... I don't know if there's any dependence, if someone can help me, I appreciate it.

**NOTE Version 4.0.11 works normally.**

![Screenshot_20210708_205553](https://user-images.githubusercontent.com/70476123/125004338-b2a25580-e02f-11eb-91ce-8134168a5733.png)
