### ISSUE TITLE
Cannot use --landscape = true option

### ISSUE THREAD

**Issue by Tin-Nguyen** [fraserxu/electron-pdf#187]
I tried many times with command line 

```
electron-pdf --input https://google.com --output ~/Desktop/test.pdf -l true -p Letter -w 2
```
However, I got the error window, then, I cannot generate the PDF with landscape
```
Shutting down...
Electron(91071,0x7fffc48183c0) malloc: *** error for object 0x7f934e6bacc0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug```

The command without `-l` option works well
```
electron-pdf --input https://google.com --output ~/Desktop/test.pdf -p Letter -w 2`

**Comment by codecounselor** [comment]
have you tried in lowercase? (`true`)

**Comment by Tin-Nguyen** [comment]
I have tried with lowercase as well. but no luck

**Comment by codecounselor** [comment]
I've reprocued it, leave true off and just set `-l` (this is what the readme shows, but the description is confusing so I will update that)

If you set DEBUG you can see the options sent to `printToPDF`
```bash
> DEBUG=electron* electron-pdf --input http://google.com --output test.pdf -l -p Letter -w 2
Thu, 27 Apr 2017 18:15:47 GMT electronpdf:debug: { marginsType: 1,
  printBackground: true,
  printSelectionOnly: false,
  pageSize: 'Letter',
  landscape: true }
Thu, 27 Apr 2017 18:15:47 GMT electronpdf:info: Export Complete
Shutting down...
```

when you set `-l true` the value becomes '`true'` which crashes things.

**Comment by Tin-Nguyen** [comment]
yeah, I tried and it works well, I see the default for landscape option is false, but it seems the lib doesn't work like that. This may still be an issue and we need to fix it

**Comment by codecounselor** [comment]
I'm not sure what you mean, please clarify.  The output should be whatever you specify (i.e. Letter) and in portrait unless you set `-l` then it becomes landscape.
What behavior are you seeing?

**Comment by Tin-Nguyen** [comment]
``` 
-l | --landscape           Boolean - true for landscape, false for portrait.
                                      false - default
```
This is the information that I receive when run `--help` command, I thought if we use `-l` only, the value is `false` by default, no?

**Comment by codecounselor** [comment]
gotcha, I updated that on master https://github.com/fraserxu/electron-pdf/blob/master/usage.txt#L16 
so the CLI help should be more clear on the next release.  Thanks, closing

**Comment by Tin-Nguyen** [comment]
thanks
