### ISSUE TITLE
Blank Output

### ISSUE THREAD

**Issue by jeffutter** [fraserxu/electron-pdf#19]
I started using electron-pdf on version 0.6. It never worked for be because of issue #11.

Now that I can get it to start the output of my pdfs are blank. I tried my own project and google.com. All i get is a single page white PDF

**Comment by fraserxu** [comment]
Fixed and tested with an url point to the issue here, let me know if you have further issue.

[report.pdf](https://github.com/fraserxu/electron-pdf/files/88884/report.pdf)
