### ISSUE TITLE
Support for multiple input (md) files

### ISSUE THREAD

**Issue by riezebosch** [fraserxu/electron-pdf#192]
`electron-pdf first.md second.md third.md single-output.pdf`

**Comment by codecounselor** [comment]
The core module (`exportJob.js`) does accept an array of inputs in it's constructor.  However, the CLI does not support more than one.
I don't use the CLI so won't be changing this anytime soon.  PR is welcome.

**Comment by riezebosch** [comment]
Working on it.

**Comment by riezebosch** [comment]
I suppose it works as intended. Multiple input files results in multiple output files. I created a workaround by combining my markdown files first using `concat`.

**Comment by codecounselor** [comment]
I actually have a use case where I combine the output, for that I use Poppler's `pdfunite` capabilities.  
http://manpages.ubuntu.com/manpages/trusty/man1/pdfunite.1.html
