### ISSUE TITLE
Add electron as a dependency?

### ISSUE THREAD

**Issue by fraserxu** [fraserxu/electron-pdf#2]
Currently you have to install electron separately if you want to use this package, I'm thinking to add electron as dependency so that user don't have to install it by himself.

The only concern is that the file size of the module will increase dramatically.

**Comment by fraserxu** [comment]
```JavaScript
var electron = require('electron-prebuilt')

// ...

var app = spawn(electron, args, { stdio: ['inherit', 'inherit', 'pipe'] })

```

**Comment by codemanki** [comment]
@fraserxu hey! thanks for your work and this great module. I want to use it inside an Electron application, and when I build my app, Electron binary is bundled inside `node_modules/electron-pdf/node_modules`. Do you know if it is somehow possible to avoid this and make electron-pdf reuse electron instance in which it is being called from? Thanks!
