### ISSUE TITLE
error while loading shared libraries: libgtk-x11-2.0.so.0

### ISSUE THREAD

**Issue by Tin-Nguyen** [fraserxu/electron-pdf#201]
Hi,

I got the issue when running electron-pdf in my server (Amazon Linux)
```
Stderr from ElectronPDF - ..../node_modules/electron-pdf/node_modules/electron/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
```

Could you give me an advise to fix it?

Thanks,
Tin Nguyen

**Comment by Tin-Nguyen** [comment]
anyone can help to resolve the issue?

**Comment by fraserxu** [comment]
First result if you Google 

https://stackoverflow.com/questions/38935024/error-while-loading-shared-libraries-libgtk-x11-2-0-so-0

**Comment by Tin-Nguyen** [comment]
@fraserxu I'm using Amazon AMI. Do you here any guidance to install the lib on the system?

**Comment by fraserxu** [comment]
Amazon AMI could be any kind of Linux distribution. So it all depends. I recommend you check the OS information first, and then try to find information on how to install for it.
