### ISSUE TITLE
The hash (#) part of urls gets stripped out

### ISSUE THREAD

**Issue by meetamit** [fraserxu/electron-pdf#202]
A job created with input url `http://www.example.com/foo#bar=baz` will end up being passed to Electron as `http://www.example.com/foo#{}`. I.e. anything after the hash gets stripped.

This removal occurs [inside the function `urlWithArgs`](https://github.com/fraserxu/electron-pdf/blob/6df5cf8d75bd38c9e2ff80938b291b592caf8a69/lib/args.js#L12-L31) from `lib/args.js`. Specifically, it is lines 18-19:

    var hash = urlData.hash || args ? args : undefined
    u = url.format(assign(urlData, { hash: hash }))

Those lines end up swapping the hash with a JSON-encoded Object `args`. Since `args` is (seemingly always) an empty object `{}`, the encoded hash becomes `#{}`.

Searching through the code, I could not find a scenario in which `args` would end up being more than an empty object, and I was unable to determine what is the reasoning behind modifying the hash in the first place. Perhaps that behavior can be removed altogether or, at minimum, perhaps line 18 is meant to be

    var hash = urlData.hash || (args ? args : undefined)

That way if there's already a hash in the input url, it is left unchanged.

P.S.

It's possible to work around this behavior without modifying electron-pdf by monkey patching `lib/args.js` from one's own `main.js`. The way I did it was by importing that module and replacing `urlWithArgs` with my own version of it:

    const argsLib = require('electron-pdf/lib/args');
    argsLib.urlWithArgs = function (urlOrFile, args) {
      /* a modified implementation of this function */
    }

**Comment by codecounselor** [comment]
I'm not really sure, this predates my involvement with the project.  It does sound like a bug though.  Probably the best thing would be to open a PR that includes test cases for the scenario(s) you are impacted by.  Unless @fraserxu thinks otherwise I would tend to agree with removing it.

**Comment by nkoterba** [comment]
Encountered the same issue as I'm trying to create a PDF of an Angular application which uses the *hash* part of the URL to correctly 'route' to the correct HTML state before taking the electron snapshot.

I agree with @meetamit that I can't figure out the purpose of this `args` property.

First, I don't think it should mutate the existing/incoming `hash` if one exists.  So agree with @meetamit that perhaps it was a classic JS bug of using `||`.

The only thing I can think of is that originally, there was a need to pass "hash-args" into `electron-pdf` when it rendered specific URLs.  I could maybe see passing in query params, but why the args mutates the **hash** part of the URL is a real head scratcher and that it also encodes the args before adding them to the hash...

Ideally, I think the urlWithArgs function could be omitted completely unless there's a need to keep it and the `_loadUrl` function in *exportJob.js* can just be:

```javascript
  /**
   * Define load options and load the URL in the window
   * @param window
   * @param url
   *
   * @private
   */
  _loadURL (window, url) {
    const loadOpts = {}
    if (this.args.disableCache) {
      loadOpts.extraHeaders += 'pragma: no-cache\n'
    }
    this.emit(`${RENDER_EVENT_PREFIX}loadurl`, { url: url })
    window.loadURL(url, loadOpts)
  }
```

I also think the associated unit test could be removed completely: https://github.com/fraserxu/electron-pdf/blob/63efba2dfc1a198c802c71357d98e4d24bbe9abc/test/args-test.js

**Comment by codecounselor** [comment]
This has broken `https` scheme because of https://github.com/fraserxu/electron-pdf/commit/ad9ad9f860e129e3369f2b836ea7fb7334d494fe#diff-30b0eaf0508dc8da9ecc1b7044f92bb1R17.  I will correct this and release a new version.
