### ISSUE TITLE
Documentation of closeWindow

### ISSUE THREAD

**Issue by denizdogan** [fraserxu/electron-pdf#207]
Thanks for this project!

The documentation says:

> If you set the inMemory setting to true, you must also set **closeWindow=true** or you will get a segmentation fault anytime the window is closed before the buffer is sent on the response. You then need to invoke job.destroy to close the window.

Then the example uses **closeWindow=false** :)

**Comment by codecounselor** [comment]
Thanks for noticing that.  It is actually the other way around.  closeWindow must be false, and it must be closed explicitly using the `job.destroy` function.  I will update the README.

**Comment by codecounselor** [comment]
Fixed in 6a2f552bcedc633c239e175d12d9330fca337417
