### ISSUE TITLE
dark gray & black background

### ISSUE THREAD

**Issue by sbellan61** [fraserxu/electron-pdf#209]
When I make PDFs I'm getting a black or very dark gray background. No idea what's going on but I didn't change the Rmd files I initially was converting at all and they started getting progressively darker over time.

[index.pdf](https://github.com/fraserxu/electron-pdf/files/1242440/index.pdf)

**Comment by codecounselor** [comment]
Were you doing this during the Solar Eclipse yesterday? 🤣

**Comment by sbellan61** [comment]
:) fortunately not

**Comment by codecounselor** [comment]
In all seriousness... can you provide some more details about what you're seeing?

- What version of electron-pdf? 
- Do you get different results by doing a bunch of consecutive runs?  Or only see this darkening over a longer period of time into the past?  
- If into the past, have you changed versions?
- I am guessing that `Rmd` is a typo and you meant you're converting markdown files, but please confirm.  Including your command and a link to your markdown might help someone to troubleshoot this.

I don't primarily do MD conversions, but I can take a quick look if you provide your source.

**Comment by codecounselor** [comment]
Closing due to no response from OP
