### ISSUE TITLE
Run electron-pdf in bash script

### ISSUE THREAD

**Issue by SidHymes** [fraserxu/electron-pdf#218]
Has anyone been successful running the program in a linux bash script on a directory/folder of html files? If so, would you be willing to post the code here?

Thanks.

**Comment by codecounselor** [comment]
It's probably dependent on your distro and the packages you have installed.  There have been a number of tickets open to address the requisite libraries.
If you post the command you're using and the error you're receiving maybe someone can help you.

**Comment by codecounselor** [comment]
Closing due to no response from OP.  Feel free to reopen if details are provided.
