### ISSUE TITLE
Upgrade to latest Electron Version (4.0.2)

### ISSUE THREAD

**Issue by codecounselor** [fraserxu/electron-pdf#231]
Its been a few years since bumping electron.  
The latest version seems to fix the previous rendering issues.

The master branch should be updated to the latest and a new 4.0.x version of electron-pdf will be published

**Comment by mrohnstock** [comment]
Great that electron got updated! But for me electron-pdf 4.0.1 won't output anything :(.

Used the following command:

```
npm install -g electron-pdf
electron-pdf https://google.com test.pdf
```

Won't finish the command and waits ... for anything? Last tested and working version was 1.2.5.

Should I open a new issue for this?

Thanks!

**Comment by codecounselor** [comment]
This is what I get.  Feel free to open an issue, but without some more details I'm not sure I can really help.
You can turn up the log levels as well, see the README.

```
 ~/projects> electron-pdf https://google.com test.pdf
Thu, 31 Jan 2019 15:47:27 GMT electronpdf:debug: { marginsType: 1,
  printBackground: true,
  printSelectionOnly: false,
  pageSize: 'A4',
  landscape: false }
Thu, 31 Jan 2019 15:47:27 GMT electronpdf:info: Export Complete
Shutting down...
```

**Comment by codecounselor** [comment]
If it helps, I noticed that on Ubuntu 18 I needed to install the `libgtk-3-common` package, which was a new requirement with the latest version of Electron.
