### ISSUE TITLE
What is the best way to embed fonts?

### ISSUE THREAD

**Issue by marcosbaroni** [fraserxu/electron-pdf#239]
I need to produce pdf using different fonts. What is the best way to embed fonts?

I've tried embedding fonts in base64 and also using "@import url('https://...')" none of those methods are working properly.

Note: I'm using electron-pdf running as a rendering service on docker container.

Thanks.

**Comment by maxkueng** [comment]
What was the solution?

**Comment by marcosbaroni** [comment]
> What was the solution?
I finally embedded them using base64 format. Example:

`@font-face {
    font-family: <font name>;
    src: url(data:font/truetype;charset=utf-8;base64,<base64 code>) format('truetype');
    font-weight: normal;
    font-style: normal;
}`

Earlier, it was not working properly because of some line breaks (generate by the base64 command) in the middle of "base64 code".
I later used the whole base64 code on a single line (`base64 -w 0`), so it finally worked properly.
