### ISSUE TITLE
How to integrate it with an electron application?

### ISSUE THREAD

**Issue by Alecyrus** [fraserxu/electron-pdf#253]
I am working on an electron application with PDF exporting feature. my application use the latest electron 6.0.10, but the electron-pdf using electron 4.x. I want to integrate electron-pdf to my application. Where should I start from?  Are there an api  in electron-pdf could receive `electron` instance?

**Comment by bruceCzK** [comment]
1. If you want electron-pdf to use other version of electron, just add the following to `package.json`
```
  "resolutions": {
    "electron-pdf/electron": "^6.0.5"
  }
```

2. Electron-pdf exposes a class, you can require it in your code like other node packages. 
For details please see https://github.com/fraserxu/electron-pdf#you-can-use-the-same-instance
```
var ElectronPDF = require('electron-pdf')
var express = require('express')
var bodyParser = require('body-parser')
var app = express()
app.use(bodyParser.json())

var exporter = new ElectronPDF()
exporter.on('charged', () => {
	//Only start the express server once the exporter is ready
	app.listen(port, hostname, function() {
		console.log(`Export Server running at http://${hostname}:${port}`);
	})
})
exporter.start()
```

**Comment by codecounselor** [comment]
@Alecyrus This project leverages the fact that Electron runs Chromium, and allows a html page to load and be printed to PDF.  It's designed to be invoked either standalone as a CLI tool or run as a service behind a (NodeJS) Api Server.

It sounds like you are trying to print to pdf from your own Electron app.  You should be able to use the following function directly: https://electronjs.org/docs/api/web-contents#contentsprinttopdfoptions-callback
