### ISSUE TITLE
Not working for Ubuntu

### ISSUE THREAD

**Issue by vasco3** [fraserxu/electron-pdf#36]
Using Ubuntu non-GUI.

>> electron-pdf template.html template2.pdf
/var/br-nodeapps/pdf-to-html/node_modules/electron-pdf/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

I installed like directed in the instructions with all the `xvfb`, etc.

**Comment by fraserxu** [comment]
You also need to start the xvfb server. Have you run all the script in the instruction?

```
$ sudo apt-get install xvfb # or equivalent
$ export DISPLAY=':99.0'
$ Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
$ electron-pdf ...
```

Also, I have another detail blog post explaining the whole process which might help as well http://webuild.envato.com/blog/running-headless-javascript-testing-with-electron-on-any-ci-server/

**Comment by vasco3** [comment]
I did start it
I'll check out the link, thanks

**Comment by bruceCzK** [comment]
Have to install libgtk too on ubuntu 14.04.
`sudo apt-get install libgtk2.0-0:i386`
