### ISSUE TITLE
CSS option

### ISSUE THREAD

**Issue by patrickdet** [fraserxu/electron-pdf#4]
As far as I can tell the CSS option is ignored. When set it gets added to the `opts` Object https://github.com/fraserxu/electron-pdf/blob/master/index.js#L70 which then later on is passed to `win.printToPDF` https://github.com/fraserxu/electron-pdf/blob/master/index.js#L108. `webContents.printToPDF` does not support the `css` option though. What it does support is `webContents.insertCSS(css)` https://github.com/atom/electron/blob/master/docs/api/web-contents.md#webcontentsinsertcsscss which should be used instead

**Comment by fraserxu** [comment]
Thanks! I'll look into at it today.

**Comment by fraserxu** [comment]
Hi @patrickdet I checked the code again, it's true that `webContents. printToPDF ` does not support `css` option, what I did is to append the `css` inside the html template

https://github.com/fraserxu/electron-pdf/blob/master/lib/markdown.js#L45-L53

so I can call `win.printToPDF` with the loaded html template, the style will apply to the page(as a normal style tag) anyhow.

I tried `webContents.insertCSS(css)` but the style is not applied to the page though.

**Comment by vweevers** [comment]
@fraserxu This seems to work:

```js
var css = [
  '@import url("https://fonts.googleapis.com/css?family=Open+Sans");',
  'body { font-family: "Open Sans" }'
].join('\n')

win.webContents.on('dom-ready', function() {
  win.webContents.insertCSS(css)
})

win.webContents.on('did-finish-load', function () {
  win.webContents.printToPDF(opts, function (err, data) {
    // ..
  })
})
```

**Comment by vweevers** [comment]
Correction, the import doesn't work, but any other CSS does.

**Comment by RamIdeas** [comment]
I got around this by dispatching a 'view-ready' event after the `document.fonts.ready` promise resolves
```html
<script>
    document.fonts.ready.then( () => document.body.dispatchEvent(new Event('view-ready')) );
</script>
```

**Comment by codecounselor** [comment]
Closing, for any circumstances such as this, the `waitForJSEvent` should be leveraged as demonstrated by @RamIdeas
