### ISSUE TITLE
Header, Footer, Page number

### ISSUE THREAD

**Issue by chrisber** [fraserxu/electron-pdf#41]

**Comment by PaddyMann** [comment]
Any plans to add this? Anyone found a workaround?

**Comment by codecounselor** [comment]
It is not likely that I will work on this anytime soon, if ever but a quick search turned up a couple interesting places in the electron source code.

https://github.com/electron/electron/blob/8359c72347372176e3cb27735caa19d967dae762/lib/browser/api/web-contents.js#L173
https://github.com/electron/electron/blob/8359c72347372176e3cb27735caa19d967dae762/lib/browser/api/web-contents.js#L63

Feel free to experiment, but I suspect this question is better targeted at the Electron project.  I don't see a way to enable this with their current API.

**Comment by PaddyMann** [comment]
Thanks for the update @codecounselor - appreciated.

Looking at how Chrome behaves, and the source code you've pointed to, it looks like it would be relatively easy for Electron to add support for headers and footers, but _not_ to make these easy to customize (e.g. in PhantomJS it's easy to specify that you just want page numbers, and the format of these).

Given that Chrome outputs much nicer PDFs, I may need to look into implementing page numbering within our app... :|

**Comment by codecounselor** [comment]
electron-pdf has no ability to control this.  Should that change it can be reopened.

**Comment by flybayer** [comment]
@PaddyMann if you have any good ideas on how to add these on the app side, please share! I'm going to need these as well :slightly_frowning_face:

**Comment by PaddyMann** [comment]
@flybayer 
I would expect to:
- Calculate the size of an A4 page in pixels
- Use a fairly flat HTML structure that makes it easy to identify elements between which I want to support page breaking
- Use JS to calculate when a page break needs to be added between 2 elements
- Use JS to create a page break that is the height of the needed gap between the last element on one page and the start of the new page, and add an element with the page number.

Massively overkill, would be nice if Chrome fixed a few bugs that prevent you adding page numbering with CSS.

PhantomJS a simpler option, or may be others?

**Comment by dcyFranck** [comment]
Hi guys,
news for this?
:(

Many thanks

**Comment by mohanzeal** [comment]
any update on this?

**Comment by mohanzeal** [comment]
I think we can use the below html, css hack to acheive look a like header and footer. Check @bsweeney comment in  the below link. Hope this helps someone!

https://github.com/dompdf/dompdf/issues/571#issuecomment-12056828
