### ISSUE TITLE
Wait for AJAX calls to complete

### ISSUE THREAD

**Issue by tquetano-r7** [fraserxu/electron-pdf#52]
Was wondering how you can set things up to wait for AJAX calls on the page to complete, so that all content has been properly loaded prior to printing?

**Comment by Remo** [comment]
on wkhtmltopdf we used a fixed delay. Not perfect as we have to be generous with the delay, but it worked okay for us. It would be nicer if we could listen to some events though!

**Comment by fraserxu** [comment]
Maybe it's better to simply pass the ajax rendered version of the html? There's no similar event like document on ready available for this as fas as I know.

**Comment by fraserxu** [comment]
Also, you don't always have control when an ajax happen on a page.

**Comment by tquetano-r7** [comment]
So we figured it out (mostly, anyway), and sadly we did not end up using this library but electron directly. I figured I would share since you may be able to incorporate it.

There is a `win.webContents` event called `did-receive-response-details`, which notifies you whenever a response is received from an AJAX call that the page makes. In Chrome, all external AJAX calls first have an `OPTIONS` call, then the response for the same URL has the appropriate call it was made with (`GET`, `POST,` etc). We set an initialWait to see if the page attempts to make any AJAX calls, and if it does then we add the URL it requested to an array. Upon response for that URL, we clear it from the array. At the initial wait period has passed, we check to see if the array is empty and if it is then we render, else poll every 200ms waiting for the array to be cleared out before rendering.

It is imperfect, but the main source of inconsistency exists in the initialWait ... as long as you give enough time for the calls to start being made and mapped appropriately, it works. It also should be more accurate than a generic timeout for the entire page.

Anyways, I'm closing the issue. Do with this information what you will. :smile:
