### ISSUE TITLE
Issues using pageSize

### ISSUE THREAD

**Issue by alexbaldwin** [fraserxu/electron-pdf#79]
Trying to print out at a specific size and am struggling.

```
electron-pdf http://localhost:8000/index.html ~/Desktop/document.pdf --printBackground --marginType 1 --landscape --pageSize '{width: 800, height: 600}'
```

Which returns the error: 

```
Error: Does not support pageSize with {width: 800, height: 600}
    at EventEmitter.webContents.printToPDF (/usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:218:25)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/electron-pdf/index.js:90:21)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
```

Can you share an example of how I should be formatting the width and height?

**Comment by codecounselor** [comment]
I found this to be a problem myself as well.  I've added some functionality to allow for height/width arguments as well as calculating them based on the pdf pageSize.  Still testing this out but I'd love to get your feedback.  Also would be more than happy to submit a PR when I'm done.

https://github.com/fraserxu/electron-pdf/compare/master...codecounselor:master

**Comment by codecounselor** [comment]
My PR was merged, so you can now set the browser dimensions in pixels.  
https://github.com/fraserxu/electron-pdf#to-specify-browser-options

You were trying to set the PDF page size which I believe is specified in microns.
