### ISSUE TITLE
Problem with new timeout feature

### ISSUE THREAD

**Issue by danieldiekmeier** [fraserxu/electron-pdf#87]
See here: https://github.com/fraserxu/electron-pdf/blob/master/index.js#L105

The `wait` parameter isn't passed to the `timeout`, but to the `did-finish-load` event.

**Comment by trevordowdle** [comment]
Good catch, I was wondering why I couldn't get it to work.

**Comment by fraserxu** [comment]
Thanks @trevordowdle @danieldiekmeier , the changes are pushed to electron-pdf@0.10.1
