### ISSUE TITLE
How can I set the exact margins?

### ISSUE THREAD

**Issue by riteme** [fraserxu/electron-pdf#93]
It seems that I can only determine the margin type (0, 1 or 2)
But in chrome it is OK to set them, and I want to have control on them (such as `margin-left`, `margin-right`, `margin-top` and `margin-bottom`).

**Comment by bruceCzK** [comment]
I think you can use CSS `@page` rule. Something like this
```
@page {
  size: A5;
  margin: 3mm;
}
```
Or media query `@media print`
See [here](https://developer.mozilla.org/en-US/docs/Web/CSS/@page) for detail.

**Comment by riteme** [comment]
Yeah, it works. Thanks a lot!
But I found that if I set page size in CSS, then the argument in command line `--landscape` will be no use.
It seems that I should write something like this if I need landscape:

```css
@page {
  size: A5 Landscape;
  margin: 3mm;
}
```

**Comment by bruceCzK** [comment]
Glad to help. And yeah it just overwrites the print config just like it does in chrome.
