### ISSUE TITLE
Chinese characters displayed messy in pdf

### ISSUE THREAD

**Issue by liu-dongyu** [fraserxu/electron-pdf#97]
Markdown ->
```markdown
# 你好吗
```

PDF ->
![2016-09-14 17-49-34](https://cloud.githubusercontent.com/assets/16187601/18507604/9eeccfd0-7aa3-11e6-9ca1-576cbadaac11.png)

Did i do something wrong or miss anything?

**Comment by fraserxu** [comment]
Have you set the `<meta charset='utf-8'>` properly in the head of your HTML?

**Comment by liu-dongyu** [comment]
Thank you for your prompt reply. But how to set '<meta charset='utf-8'>' in a .md file ？

**Comment by fraserxu** [comment]
Hmm, this could be an issue. I'll try a Chinese file and see.

**Comment by fraserxu** [comment]
@liu-dongyu Fix and pushed to v0.11.0 Please let me know if the issue is still happening.

**Comment by liu-dongyu** [comment]
Works great now. I love electron-pdf.
